@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 15 17:55:58 +0100 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim SYNCHRNZR_tb_behav -key {Behavioral:sim_1:Functional:SYNCHRNZR_tb} -tclbatch SYNCHRNZR_tb.tcl -view C:/Users/davil/Cafetera/Trabajo-VHDL/Cafetera_2/Top_tb_inicial.wcfg -view C:/Users/davil/Cafetera/Trabajo-VHDL/Cafetera_2/SYNCHRNZR_tb_final.wcfg -log simulate.log"
call xsim  SYNCHRNZR_tb_behav -key {Behavioral:sim_1:Functional:SYNCHRNZR_tb} -tclbatch SYNCHRNZR_tb.tcl -view C:/Users/davil/Cafetera/Trabajo-VHDL/Cafetera_2/Top_tb_inicial.wcfg -view C:/Users/davil/Cafetera/Trabajo-VHDL/Cafetera_2/SYNCHRNZR_tb_final.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
